services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development-stage
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_USE_POLLING=true
    ports:
      - "5174:5174"
  backend:
    profiles:
      - backend
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongo://db:27017
  database:
    profiles:
      - backend
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - db-data:/data/db

volumes:
  db-data:
