name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: whodrey-labs/homelab-actions/.github/workflows/deploy-homelab.yml@main
    with:
      branch: main
      use_tailscale: true
    secrets: inherit
